"""empty message

Revision ID: 6221336f31a4
Revises: c6dd25339eae
Create Date: 2021-11-08 23:07:25.811787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6221336f31a4'
down_revision = 'c6dd25339eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=300), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('phone_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=300), nullable=True),
    sa.Column('address', sa.VARCHAR(length=500), nullable=True),
    sa.Column('phone_number', sa.INTEGER(), nullable=True),
    sa.Column('date_created', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact')
    # ### end Alembic commands ###
