"""empty message

Revision ID: e05f10b8f426
Revises: 6221336f31a4
Create Date: 2021-11-09 19:57:17.477347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05f10b8f426'
down_revision = '6221336f31a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['date_created'], ['id'])
    # ### end Alembic commands ###
